# GitHub dependabot dependency management configuration file

version: 2
updates:
  # Composer
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: weekly
    ignore:
      - dependency-name: 'phpunit/phpunit'
        update-types: ["version-update:semver-patch"]
      - dependency-name: 'phpstan/phpstan'
        update-types: ["version-update:semver-patch"]
